### ISSUE TITLE
查看长图片的问题

### ISSUE THREAD

**Issue by stattrak-dragonlore** [Sunnyyoung/SYPhotoBrowser#2]
长图片情况下，滚动(scroll)操作 跟  滚动消失手势 应该有冲突。。

试下浏览大图就知道了

**Comment by sunnyyoung** [comment]
@dengzhp 最近忙，Pull最新Demo试试看

**Comment by stattrak-dragonlore** [comment]
试了，有时候OK，有些时候不行（放大图片后：上下滚动失效，左右滚动变成切换，不是想要的滚动查看其它区域），概率还不低。

**Comment by sunnyyoung** [comment]
@dengzhp 我也发现了＝ ＝，已修复
